version: "3"
services:

  proxy:
    image: nubie13/proxy-prod:v1
    networks:
      - ext_net
      - proxy_net
    ports:
      - '80:80'
    volumes:
      - data_proxy:/etc/nginx/conf.d/

  web:
    image: nubie13/web-prod:v1
    networks:
      - proxy_net
      - int_net
    volumes:
      - data_web:/var/www/html
    depends_on:
      - mysql
    
  pma:
    image: nubie13/pma-prod:v1
    networks:
      - proxy_net
      - int_net
    environment:
      PMA_HOST: mysql
    volumes:
      - data_pma:/etc/phpmyadmin
    depends_on:
      - mysql
    
  mysql:
    image: nubie13/mysql-prod:v1
    networks:
      - int_net
    environment:
      MYSQL_ROOT_PASSWORD: makinganteng
      MYSQL_DATABASE: dbkuasai
      MYSQL_USER: cilsykuasaiuser
      MYSQL_PASSWORD: cilsykuasaipassword
    volumes:
      - data_mysql:/var/lib/mysql
      
networks:
  ext_net:
  proxy_net:
  int_net:
  
      
volumes:
  data_proxy:
  data_web:
  data_mysql:
  data_pma: